logicalclocks/hopslog-chef

Berksfile, Karamelfile, metadata.rb, recipes/_logstash.rb, templates/default/app.log4j.properties.erb
Create log4j.properties with logstash ip and put to hdfs
https://hopshadoop.atlassian.net/browse/HOPSWORKS-185
=> HOPSWORKS-185

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-652
=> [HOPSWORKS-652]  Change primary group of yarn user

recipes/_kibana.rb, templates/default/hops_upgrade_060.sh.erb
move upgrade curl commands to script
=> HOPSWORKS-757

recipes/_kibana.rb
lower case project names, run only if version is 0.6.x
=> HOPSWORKS-757 append

Karamelfile, attributes/default.rb, metadata.rb, recipes/_filebeat-kagent.rb, recipes/_logstash.rb, templates/default/kagent.conf.erb, templates/default/pipelines.yml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-916
=> [HOPSWORKS-916] Show failure message for Conda commands

.gitignore, attributes/default.rb, metadata.rb, recipes/_filebeat-serving.rb, recipes/_logstash.rb, templates/default/pipelines.yml.erb, templates/default/sklearn_serving.conf.erb, templates/default/tf_serving.conf.erb
- serving user name and group updated
- configure filebeat for sklearn serving
- configure logstash for sklearn serving
=> [HOPSWORKS-751] Add SkLearn model serving

recipes/_kibana.rb, recipes/_logstash.rb, templates/default/kibana.service.erb, templates/default/logstash.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1091
=> [HOPSWORKS-1091] Add systemd.unit deps

Karamelfile, attributes/default.rb, metadata.rb, recipes/_filebeat-beam.rb, recipes/_filebeat-serving.rb, recipes/_logstash.rb, templates/default/beamjobserver.conf.erb, templates/default/beamsdkworker.conf.erb, templates/default/pipelines.yml.erb
- Add filebeat for Beam JobServer local
- Add filebeat for Beam JobServer cluster (when in Spark/PySpark)
- Add filebeat for Beam SDKWorker
- Add logstash for the aforementioned filebeats
=> [HOPSWORKS-640] Flink/Beam

recipes/_filebeat-beam.rb, recipes/_filebeat-kagent.rb, recipes/_filebeat-serving.rb, recipes/_filebeat-spark.rb, recipes/_kibana.rb, recipes/_logstash.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1331
=> [HOPSWORKS-1331] Consistent flag for system upgrades

recipes/_logstash.rb, templates/default/beamjobserver.conf.erb, templates/default/beamsdkworker.conf.erb, templates/default/kagent.conf.erb, templates/default/sklearn_serving.conf.erb, templates/default/spark-streaming.conf.erb, templates/default/tf_serving.conf.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1027
tests: https://github.com/logicalclocks/hops-testing/pull/512
=> [HOPSWORKS-1027] Add support for multiple elasticsearch nodes (HA)

recipes/_filebeat-beam.rb, recipes/_filebeat-kagent.rb, recipes/_filebeat-serving.rb, recipes/_filebeat-spark.rb, templates/default/filebeat.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1457
=> [HOPSWORKS-1457] fix systemd script

recipes/_kibana.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1528
tests: https://github.com/logicalclocks/hops-testing/pull/597
=> [HOPSWORKS-1528] Remove unnecessary code to set kibana default index

recipes/_filebeat-beam.rb, recipes/_filebeat-spark.rb, templates/default/beamjobserver.conf.erb, templates/default/beamsdkworker.conf.erb, templates/default/filebeat.yml.erb
1. Fix loggers for beam broken due to upgrade to ELK 7.2
2. Fix multiline patter for beam loggers
=> [HOPSWORKS-1493] Beam logger fixes

Berksfile, Karamelfile, attributes/default.rb, recipes/_filebeat-beam.rb, recipes/_filebeat-kagent.rb, recipes/_filebeat-serving.rb, recipes/_filebeat-spark.rb, recipes/_logstash.rb, templates/default/consul/logstash-consul.hcl.erb, templates/default/consul/logstash-health.sh.erb, templates/default/start-logstash.sh.erb
https://github.com/logicalclocks/hops-testing-ee/pull/46
=> [HOPSWORKS-1728] Register Logstash with Consul

recipes/_filebeat-serving.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1694
=> [HOPSWORKS-1694] run user code in docker

attributes/default.rb, metadata.rb, recipes/_kibana.rb, recipes/_logstash.rb, templates/default/beamjobserver.conf.erb, templates/default/beamsdkworker.conf.erb, templates/default/kibana.yml.erb, templates/default/kube_jobs.conf.erb, templates/default/sklearn_serving.conf.erb, templates/default/spark-streaming.conf.erb, templates/default/tf_serving.conf.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657
=> [HOPSWORKS-1657] System users x.509 v2

recipes/_kibana.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1977
=> [HOPSWORKS-1977] Replace kagent/test with kagent/enabled

templates/default/filebeat.service.erb, templates/default/kibana.service.erb, templates/default/logstash.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
=> [HOPSWORKS-2065] Automatically restart failed systemd units

attributes/default.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
=> [HOPSWORKS-2578] Logstash, Kibana, Filebeat logs and data to data volume

recipes/_filebeat-services.rb, templates/default/kibana-consul.hcl.erb
[HOPSWORKS-2748] Use logstash Consul domain name instead of IP address
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2748
[HOPSWORKS-2748]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2748
=> [HOPSWORKS-2748] Fix Kibana's consul service health check

attributes/default.rb, metadata.rb, recipes/_logstash.rb, templates/default/pipelines.yml.erb, templates/default/services.conf.erb
Needed by https://github.com/logicalclocks/hopsworks-cloud/pull/2533
=> Hopsworks cloud 2527

attributes/default.rb, metadata.rb, recipes/_logstash.rb, templates/default/logstash.yml.erb, templates/default/logstash_jvm.options.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-3016
=> [HOPSWORKS-3016] Improve Resource consumption configurability for Logstash, change defaults. 

attributes/default.rb, metadata.rb, templates/default/logstash.yml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-3025
Relates to https://github.com/logicalclocks/hopsworks-cloud/issues/2809
=> [HOPSWORKS-3025] Remove unrecognized settings in Logstash 7.2

attributes/default.rb, recipes/install.rb
Fixes https://logicalclocks.atlassian.net/browse/HOPSWORKS-3019
=> [HOPSWORKS-3019] Point filebeat data to the correct data directory

templates/default/logstash.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-3060
=> [HOPSWORKS-3060] increase nice level of logstash to 19

attributes/default.rb, metadata.rb, recipes/_filebeat-spark.rb, recipes/_logstash.rb, templates/default/jupyter.conf.erb, templates/default/logstash_log4j2.properties.erb, templates/default/services.conf.erb, templates/default/serving.conf.erb, templates/default/spark-streaming.conf.erb
https://hopsworks.atlassian.net/browse/HOPSWORKS-3222
=> Refactor logstash pipelines to improve CPU untilization

templates/default/consul/logstash-health.sh.erb
Fixes https://hopsworks.atlassian.net/browse/HWORKS-168
=> [HWORKS-168] Override error exit code

templates/default/services.conf.erb
https://hopsworks.atlassian.net/browse/CLOUD-175
=> [CLOUD-175] Collect RonDB logs in Logstash

recipes/_filebeat-services.rb, templates/default/services.conf.erb
https://hopsworks.atlassian.net/browse/CLOUD-186
=> [CLOUD-186] Collect ePipe logs in Logstash

templates/default/services.conf.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-504
=> [CLOUD-504] Fix date template for hadoop services

attributes/default.rb, templates/default/stop-logstash.sh.erb
https://hopsworks.atlassian.net/browse/HWORKS-659
=> [HWORKS-659] Use the tmp_directory attribute

templates/default/filebeat.service.erb
https://hopsworks.atlassian.net/browse/HWORKS-946
=> [HWORKS-946] Extra After systemd units
